const LEAGUE='1395507776981069824';
const base='https://api.sleeper.app/v1';
const get=async p=>{const r=await fetch(base+p,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`${p}: ${r.status}`);return r.json()};
const [state,league,users,rosters]=await Promise.all([get('/state/nfl'),get(`/league/${LEAGUE}`),get(`/league/${LEAGUE}/users`),get(`/league/${LEAGUE}/rosters`)]);
const week=Number(state.leg??state.week);
if(String(league.season)!==String(state.season)) throw new Error(`Season mismatch NFL ${state.season} vs league ${league.season}`);
if(league.league_id!==LEAGUE||rosters.length!==12) throw new Error('League identity or roster count mismatch');
const [rows,txs,players]=await Promise.all([get(`/league/${LEAGUE}/matchups/${week}`),get(`/league/${LEAGUE}/transactions/${week}`),get('/players/nfl')]);
if(!Array.isArray(rows)||rows.length!==12) throw new Error(`Expected 12 matchup rows, got ${rows?.length}`);
const byUser=Object.fromEntries(users.map(u=>[u.user_id,u])),byRoster=Object.fromEntries(rosters.map(r=>[r.roster_id,r]));
const pname=id=>players[id]?.full_name||[players[id]?.first_name,players[id]?.last_name].filter(Boolean).join(' ')||id;
const mgr=rid=>{const r=byRoster[rid],u=byUser[r?.owner_id];return {roster_id:rid,display:u?.display_name||'',team:((u?.metadata?.team_name||'').trim()||u?.display_name||`Roster ${rid}`),co:(r?.co_owners||[]).map(id=>byUser[id]?.display_name||id),record:r?.metadata?.record||'',streak:r?.metadata?.streak||'',wins:r?.settings?.wins||0,losses:r?.settings?.losses||0,ties:r?.settings?.ties||0,pf:(r?.settings?.fpts||0)+(r?.settings?.fpts_decimal||0)/100,pa:(r?.settings?.fpts_against||0)+(r?.settings?.fpts_against_decimal||0)/100,potential:(r?.settings?.ppts||0)+(r?.settings?.ppts_decimal||0)/100,waiver_used:r?.settings?.waiver_budget_used||0,players:(r?.players||[]).map(pname)}};
const standings=rosters.map(r=>mgr(r.roster_id)).sort((a,b)=>b.wins-a.wins||a.losses-b.losses||b.pf-a.pf);
const groups={};for(const x of rows)(groups[x.matchup_id]??=[]).push(x);
const matchups=Object.entries(groups).sort((a,b)=>Number(a[0])-Number(b[0])).map(([id,rs])=>({id:Number(id),teams:rs.map(x=>{const m=mgr(x.roster_id);return {roster_id:x.roster_id,display:m.display,team:m.team,co:m.co,record:m.record,streak:m.streak,current_points:x.custom_points??x.points??0,empty:(x.starters||[]).filter(v=>!v||v==='0').length,starters:(x.starters||[]).map((pid,i)=>({name:pid&&pid!=='0'?pname(pid):'EMPTY',nfl_team:players[pid]?.team||'',position:players[pid]?.position||'',points:(x.players_points||{})[pid]??(x.starters_points||[])[i]??0}))}})}));
const transactions=(txs||[]).filter(t=>t.status==='complete').map(t=>({type:t.type,status_updated:t.status_updated,adds:Object.entries(t.adds||{}).map(([p,r])=>[pname(p),mgr(r).team]),drops:Object.entries(t.drops||{}).map(([p,r])=>[pname(p),mgr(r).team]),waiver_budget:t.waiver_budget||[],settings:t.settings||{},roster_ids:t.roster_ids||[]}));
console.log('LIVE_READ_BEGIN');
console.log(JSON.stringify({checked_at:new Date().toISOString(),state:{season:state.season,week,season_type:state.season_type},league:{id:league.league_id,name:league.name,season:league.season,status:league.status,total_rosters:league.total_rosters},standings,matchups,transactions}));
console.log('LIVE_READ_END');
throw new Error('Research-only stop after live read; no render or publish.');
