import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
const root=process.cwd(),pub=path.join(root,'public');let checks=0;const failures=[];
function ok(c,l){checks++;if(!c)failures.push(l)}function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const p=path.join(d,e.name);return e.isDirectory()?walk(p):[p]})}function text(f){return fs.readFileSync(f,'utf8')}function rel(f){return path.relative(root,f).replaceAll('\\','/')}function targetExists(from,raw){let v=raw.split('#')[0].split('?')[0];if(!v||v.startsWith('#')||/^(https?:|mailto:|tel:|javascript:|data:)/i.test(v))return true;if(v.startsWith('/'))return true;const p=path.resolve(path.dirname(from),v);return fs.existsSync(p)||(!path.extname(p)&&fs.existsSync(`${p}.html`))}
const files=walk(pub),html=files.filter(f=>f.endsWith('.html')),js=files.filter(f=>f.endsWith('.js')),css=files.filter(f=>f.endsWith('.css'));
ok(fs.existsSync(pub),'public directory exists');ok(html.length>=10,`at least 10 HTML pages exist (found ${html.length})`);ok(js.length>=8,`at least 8 JS files exist (found ${js.length})`);ok(css.length>=8,`at least 8 CSS files exist (found ${css.length})`);
for(const file of files)ok(fs.statSync(file).size>0||path.basename(file)==='.nojekyll',`${rel(file)} is not unexpectedly empty`);
for(const file of html){const s=text(file);ok(/<!doctype html>/i.test(s),`${rel(file)} has doctype`);ok(/<meta[^>]+name=["']viewport["']/i.test(s)||path.basename(file)==='index.html',`${rel(file)} has viewport metadata`);ok(/<title>[^<]+<\/title>/i.test(s),`${rel(file)} has title`);const ids=[...s.matchAll(/\bid=["']([^"']+)["']/gi)].map(m=>m[1]);ok(new Set(ids).size===ids.length,`${rel(file)} has no duplicate ids`);for(const m of s.matchAll(/\b(?:href|src)=["']([^"']+)["']/gi))ok(targetExists(file,m[1]),`${rel(file)} target exists: ${m[1]}`)}
for(const file of js){try{execFileSync(process.execPath,['--check',file],{stdio:'pipe'});ok(true,`${rel(file)} parses as JavaScript`)}catch{ok(false,`${rel(file)} parses as JavaScript`)}}for(const file of css){const s=text(file);ok((s.match(/{/g)||[]).length===(s.match(/}/g)||[]).length,`${rel(file)} has balanced CSS braces`)}
const index=text(path.join(pub,'index.html')),draft=text(path.join(pub,'draft-table.html')),draftJs=text(path.join(pub,'draft-table.js')),home=text(path.join(pub,'home.html')),homeJs=text(path.join(pub,'locker-room.js')),leaders=text(path.join(pub,'leaderboards.html')),polls=text(path.join(pub,'polls.js')),gauntlet=text(path.join(pub,'gauntlet.html')),premiere=text(path.join(pub,'premiere.html')),order=text(path.join(pub,'draft-order.html')),recap=text(path.join(pub,'draft-recap.html')),films=text(path.join(pub,'film-room.html')),orderJs=text(path.join(pub,'draft-order.js'));
ok(index.includes('draft-recap.html')&&index.includes('g24_postdraft_2026_seen'),'root launches current post-draft premiere exactly once');ok(premiere.includes('Official 2026 Sleeper Draft Order'),'Opening film remains preserved with official draft order');ok(order.includes('permanent official board'),'Draft Order page is permanent archive board');ok(!order.includes('100-move race'),'Old race copy removed from public order page');ok(draft.includes('id="teamCheck"'),'Draft Table retains manager identity records');ok(draftJs.includes('api.sleeper.app/v1/league'),'Draft records verify against Sleeper API');ok(draftJs.includes('g24_member_name'),'Draft Table uses shared site identity key');ok(home.includes('THE<br/><em>LOCKER ROOM</em>'),'Locker Room has over-produced hero');ok((home.match(/class="locker/g)||[]).length>=4,'Locker Room exposes four season lockers');ok(home.includes('draft-recap.html'),'Locker Room launches post-draft recap');ok(home.includes('games.html'),'Locker Room launches season games');ok(home.includes('leaderboards.html'),'Locker Room launches leaderboards');ok(home.includes('draft-order.html'),'Locker Room preserves draft archive');ok(home.includes('film-room.html'),'Locker Room permanently exposes the Film Room');ok(films.includes('premiere.html')&&films.includes('draft-recap.html'),'Film Room preserves both official league films');ok(home.includes('The inaugural record is officially underway.'),'Homepage is visibly in season mode');ok(!home.includes('player-scene')&&!home.includes('bench-player'),'Locker Room ships without experimental player illustrations');ok(homeJs.includes("fetch('./sleeper-verified.json'")&&homeJs.includes("Draft: complete"),'Locker Room reads the verified completed Sleeper draft snapshot');ok(homeJs.includes('AudioContext'),'Locker Room contains synthesized interaction sound');ok(recap.includes('THE DRAFT<br/><em>IS CLOSED.</em>'),'Post-draft recap page exists');ok(recap.includes('<video')&&recap.includes('video/mp4'),'Recap page contains the finished post-draft film');ok(orderJs.includes("String(d.season)==='2026'")||orderJs.includes('sleeper-draft-2026.json'),'Draft board is pinned to the official 2026 Sleeper draft');ok(leaders.includes('Gridiron Gauntlet'),'Leaderboard page includes Gauntlet board');ok(leaders.includes('Read the Room'),'Leaderboard page includes side-game board');ok(leaders.includes('Bold Predictions'),'Leaderboard page includes prediction scoring section');ok(polls.includes('g24_member_name'),'Polls reuse shared 24 Gridiron identity');ok(gauntlet.includes('identity.js'),'Gauntlet loads shared identity helper');ok(!home.includes('Ticket code'),'Locker Room has no ticket-code gate');ok(checks>=100,`release gate executes at least 100 checks (ran ${checks} before threshold assertion)`);
if(failures.length){console.error(`\nQA FAILED: ${failures.length} of ${checks} checks failed\n`);failures.forEach((f,i)=>console.error(`${i+1}. ${f}`));process.exit(1)}console.log(`QA PASSED: ${checks} checks`);
