import React from 'react';
import {registerRoot,Composition,AbsoluteFill,Audio,staticFile,useCurrentFrame,interpolate,spring,useVideoConfig} from 'remotion';
const FPS=30,DUR=225;
const fallback=Array.from({length:12},(_,i)=>({pick:i+1,name:`DRAFT SLOT ${i+1}`}));
const COLORS=['#e9b949','#d9772b','#b9a36a','#9e5a37','#e2c675','#8e9b72','#c78b48','#b5a284','#d2a84a','#a86d3d','#d7bf7b','#927b5a'];
const hash=s=>[...String(s)].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,2166136261);
function rng(seed){let x=seed||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)%100000)/100000}}
function race(teams){const r=rng(hash(teams.map(x=>x.name).join('|'))),scores=teams.map(()=>0),turns=[];for(let turn=1;turn<=100;turn++){const rolls=teams.map((t,i)=>{let roll=1+Math.floor(r()*6);if(turn>82){const desired=13-t.pick;const rank=[...scores].sort((a,b)=>b-a).indexOf(scores[i]);if(desired<=4&&rank>desired+2)roll=Math.max(roll,5);if(desired>=9&&rank<desired-3)roll=Math.min(roll,2)}scores[i]+=roll;return roll});turns.push({rolls,scores:[...scores]})}const target=teams.map(t=>13-t.pick);const sorted=[...scores].sort((a,b)=>a-b);teams.forEach((t,i)=>scores[i]=sorted[target[i]-1]);turns[99].scores=[...scores];return turns}
const fit=n=>n.length>24?24:n.length>18?28:32;
function App(){let data;try{data=require('../public/order.json')}catch{}const teams=data?.teams?.length===12?data.teams:fallback;return <Composition id="DraftReveal" component={Reveal} durationInFrames={DUR*FPS} fps={FPS} width={1920} height={1080} defaultProps={{teams}}/>}
function Reveal({teams}){const f=useCurrentFrame(),{fps}=useVideoConfig(),t=f/fps,turns=React.useMemo(()=>race(teams),[teams]);const intro=t<24,final=t>=204;const raceStart=24,raceEnd=184;const turn=Math.max(0,Math.min(99,Math.floor((t-raceStart)/(raceEnd-raceStart)*100)));const prog=Math.max(0,Math.min(1,(t-raceStart)/(raceEnd-raceStart)));const cur=turns[turn]||turns[0];const max=Math.max(...cur.scores,1);const rank=[...teams].sort((a,b)=>cur.scores[teams.indexOf(b)]-cur.scores[teams.indexOf(a)]);const leader=rank[0];const die=cur.rolls[teams.indexOf(leader)];return <AbsoluteFill style={{background:'#050b08',color:'#f4ead2',fontFamily:'Arial, sans-serif',overflow:'hidden'}}><Audio src={staticFile('score.wav')}/><div style={{position:'absolute',inset:0,background:'radial-gradient(circle at 50% 30%,#183529 0,#07120d 42%,#020504 100%)'}}/><div style={{position:'absolute',inset:0,opacity:.13,backgroundImage:'repeating-linear-gradient(0deg,transparent 0 58px,#d9b45c 59px 60px)'}}/>{intro?<Intro t={t} teams={teams}/>:final?<Final t={t-204} teams={teams}/>:<Race t={t} turn={turn} teams={teams} cur={cur} max={max} leader={leader} die={die} prog={prog}/>}</AbsoluteFill>}
function Intro({t,teams}){const a=Math.min(1,t/2),names=t>12;return <><div style={{position:'absolute',top:90,left:100,fontSize:22,letterSpacing:8,color:'#d7b65a'}}>24 GRIDIRON · INAUGURAL SEASON</div><div style={{position:'absolute',left:100,right:100,top:250,opacity:a}}><div style={{fontSize:112,fontWeight:900,lineHeight:.9}}>THE 100-MOVE</div><div style={{fontSize:154,fontWeight:900,lineHeight:.9,color:'#d7b65a'}}>DRAFT DASH</div><div style={{fontSize:26,letterSpacing:6,marginTop:34}}>12 MANAGERS · 100 MOVES · ONE OFFICIAL ORDER</div></div>{names&&<div style={{position:'absolute',left:105,right:105,bottom:80,display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:10}}>{teams.map((x,i)=><div key={i} style={{borderTop:'2px solid #d7b65a',paddingTop:10,fontWeight:800,fontSize:20}}>{x.name}</div>)}</div>}</>}
function Race({t,turn,teams,cur,max,leader,die,prog}){const late=turn>=90;return <><div style={{position:'absolute',top:38,left:70,right:70,display:'flex',justifyContent:'space-between',alignItems:'end'}}><div><div style={{fontSize:18,letterSpacing:5,color:'#d7b65a'}}>THE 100-MOVE DRAFT DASH</div><div style={{fontSize:58,fontWeight:900}}>MOVE {turn+1}<span style={{opacity:.35}}>/100</span></div></div><div style={{textAlign:'right'}}><div style={{fontSize:16,letterSpacing:4,opacity:.55}}>CURRENT LEADER</div><div style={{fontSize:32,fontWeight:900}}>{leader.name}</div></div></div><div style={{position:'absolute',left:70,right:70,top:155,bottom:95}}>{teams.map((x,i)=>{const p=cur.scores[i]/max;const pos=interpolate(p,[0,1],[1,91]);return <div key={x.pick} style={{position:'absolute',top:i*65,height:54,left:0,right:0,borderBottom:'1px solid #315040'}}><div style={{position:'absolute',left:`${pos}%`,transform:'translateX(-100%)',width:late?300:250,height:46,borderRadius:4,background:`linear-gradient(90deg,#16251d,${COLORS[i]})`,boxShadow:'0 6px 20px #0009',display:'flex',alignItems:'center',gap:10,padding:'0 12px'}}><span style={{width:32,height:32,borderRadius:'50%',background:'#f0e5cb',color:'#101713',display:'grid',placeItems:'center',fontWeight:900}}>{i+1}</span><b style={{fontSize:fit(x.name),whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{x.name}</b></div></div>})}<div style={{position:'absolute',right:'5%',top:0,bottom:0,borderLeft:'5px dashed #d7b65a'}}><span style={{position:'absolute',top:-28,left:-45,fontSize:14,letterSpacing:4}}>FINISH</span></div></div><div style={{position:'absolute',bottom:25,left:70,right:70,display:'flex',alignItems:'center',gap:22}}><div style={{width:68,height:68,background:'#eee2c7',color:'#101713',borderRadius:12,display:'grid',placeItems:'center',fontSize:42,fontWeight:900,transform:`rotate(${(turn%4-2)*4}deg)`}}>{die}</div><div><b style={{fontSize:22}}>{late?'EVERY MOVE MATTERS NOW':turn>65?'THE FIELD IS BREAKING APART':turn>30?'NO LEAD IS SAFE':'CHAOS OFF THE LINE'}</b><div style={{fontSize:15,letterSpacing:3,opacity:.55}}>OFFICIAL ORDER SET IN SLEEPER · RACE IS THE REVEAL</div></div><div style={{marginLeft:'auto',fontSize:28,fontWeight:900,color:'#d7b65a'}}>{Math.round(prog*100)}%</div></div></>}
function Final({t,teams}){const reveal=Math.min(12,Math.max(0,Math.floor((t-2)/1.05)));const climax=t>15;return <><div style={{position:'absolute',inset:0,display:'grid',placeItems:'center',textAlign:'center'}}>{t<2?<div><div style={{fontSize:30,letterSpacing:9,color:'#d7b65a'}}>ONE HUNDRED MOVES LATER</div><div style={{fontSize:110,fontWeight:900}}>THE ORDER IS SET.</div></div>:<div style={{width:1200}}><div style={{fontSize:22,letterSpacing:7,color:'#d7b65a',marginBottom:20}}>2026 OFFICIAL DRAFT ORDER</div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:'8px 35px'}}>{[...teams].sort((a,b)=>b.pick-a.pick).slice(0,reveal).map(x=><div key={x.pick} style={{display:'flex',alignItems:'center',borderBottom:'1px solid #4c5c51',padding:'8px 0',fontSize:x.pick===1&&climax?38:25,color:x.pick===1&&climax?'#e7bd55':'#f4ead2'}}><b style={{width:65,fontSize:x.pick===1&&climax?48:30}}>{x.pick}</b><span style={{fontWeight:900}}>{x.name}</span></div>)}</div>{climax&&<div style={{marginTop:28,fontSize:27,letterSpacing:6,fontWeight:900}}>TUESDAY · SEPTEMBER 8 · 3:00 PM PACIFIC</div>}</div>}</div></>}
registerRoot(App);
